### PR TITLE
More fixes for error handling

### LINKED ISSUE #99: travis.sh terminates travis job, no post-process script is run
I figured that the postprocess is never run because we `exit` from a sourced script.
Why do we source travis.sh instead of calling it?

### PR DESCRIPTION
**Pull request by ipa-mdl**
It turned out that #100 did not fix #99 completely.
`error()` did exit the travis-generated script as well.
Lesson learned: never `exit` from a `source`d script.

So `ci_main.sh` does not get sourced anymore; environment is no longer exposed.
That's why I have added `AFTER_SCRIPT`.
Please note: Additional scripts added in .travis.yml do not get executed in docker container!

Travis executes all `script:` lines regardless of the exit code, but marks the build as failed if one line failed.
However, this might change: https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-257441420

### CODE REVIEW

**Comment by ipa-mdl** [comment]
now it was easy to implement an exit code check (supersedes #80)

**Comment by ipa-mdl** [comment]
Perhaps `AFTER_SCRIPT` should only be executed in `source_tests.sh` (like `BEFORE_SCRIPT`).

**Comment by ipa-mdl** [comment]
rebased

File: industrial_ci/util.sh [hunk 1]
```diff
@@ -86,15 +86,14 @@ function _end_fold_script {
...
+    if ! [ -z $TRAVIS_FOLD_NAME ]; then
         ici_time_end $color_wrap
     else
 	echo "Previous Travis fold name not found. It might be either successful termination of the script, or wrong call. Skipping 'ici_time_end' anyway."
     fi
 
-    if [ $exit_code -eq "1" ]; then trap - ERR; fi  # Reset signal handler since the shell is about to exit.
     if [ "$DEBUG_BASH" ] && [ "$DEBUG_BASH" == true ]; then set -x; fi
-    if [ $exit_code -ne "-1" ]; then exit $exit_code; fi
+    if [ $exit_code -ne "-1" ]; then ici_exit $exit_code; fi
```
Comment (130s) [inline industrial_ci/util.sh]: Depending on situation, calling this function can fail where `ici_exit` is not yet loaded.

Comment (ipa-mdl) [inline industrial_ci/util.sh]: I cannot think of a situation like this, do you have an example.
I can move `ici_exit`to the top if you prefer it..

**Comment by ipa-mdl** [comment]
Do not merge yet, I'd like to add error tracing and the error function needs to get modified for exit code propagation

File: industrial_ci/util.sh [hunk 2]
```diff
@@ -86,15 +86,14 @@ function _end_fold_script {
     color_wrap=${2:-32}
 
     if [ $exit_code -eq "1" ]; then color_wrap=31; fi  # Red color
-    if [ -z $TRAVIS_FOLD_NAME ]; then
+    if ! [ -z $TRAVIS_FOLD_NAME ]; then
```
Comment (130s) [inline industrial_ci/util.sh]: If this change is intended, the following else block may no longer make sense.

File: industrial_ci/ci_main.sh [hunk 3]
```diff
@@ -52,7 +52,7 @@ export HIT_ENDOFSCRIPT=false
 
 source ${ICI_PKG_PATH}/util.sh
 
-trap error ERR
+trap error EXIT
```
Comment (130s) [inline industrial_ci/ci_main.sh]: Do we want to create a new function `exit`? Isn't trapping `EXIT` with `error` function misleading?

Comment (ipa-mdl) [inline industrial_ci/ci_main.sh]: Good idea, will add this later

File: industrial_ci/util.sh (hunk 1 above)
Comment (130s) [inline industrial_ci/util.sh]: I don't have a usecase for now, but only because this file is "util" we better address all the possibility we can think of.
Moving `ici_exit` sounds good to me.

File: industrial_ci/util.sh (hunk 2 above)
Comment (ipa-mdl) [inline industrial_ci/util.sh]: It is intended, but the else block still makes sense.
` if ! [ -z $TRAVIS_FOLD_NAME ]` -> `if $TRAVIS_FOLD_NAME is not empty` -> `if fold is open`
This is the bug I did not find in #100

File: industrial_ci/util.sh (hunk 1 above)
Comment (ipa-mdl) [inline industrial_ci/util.sh]: I guess `ici_exit` will be refactored to become the exit handler

**Comment by ipa-mdl** [comment]
> Does this change require to change .travis.yml in users' repos, from like source .ci_config/travis.sh to .ci_config/travis.sh

No, `source travis.sh` is still supported. We might add a warning in this case since the enviroment is not exported anymore

> Sorry but I can't remember why BEFORE_SCRIPT is run from source_tests.sh

This way it is called after ROS and workspace set-up.

> Perhaps AFTER_SCRIPT should only be executed in source_tests.sh (like BEFORE_SCRIPT).

I guess this will change with #98 anyway: It works for now, we should not touch it for now.

File: industrial_ci/util.sh (hunk 2 above)
Comment (130s) [inline industrial_ci/util.sh]: Ah, I see. Turned out I've been consistently misunderstanding `if -z` option.

**Comment by 130s** [comment]
I see. +1 from me.
Minor todos can be addressed in the future in you like to merge this one first @ipa-mdl.

File: industrial_ci/util.sh (hunk 2 above)
Comment (ipa-mdl) [inline industrial_ci/util.sh]: `if [ -n $TRAVIS_FOLD_NAME ]` ("not empty") might be easier to understand ^^

**Comment by ipa-mdl** [comment]
Error-code related refactoring completed :)
Now every fold lists an exit code and `error` forwards the exit code if possible.
`ici_exit` is the default exit handler and closes open folds

File: industrial_ci/util.sh [hunk 4]
```diff
@@ -51,93 +51,76 @@ function ici_time_start {
...
-    	if [ $_exit_code -eq 0 ]; then
-    	    echo "${_FUNC_MSG_PREFIX} Arg HIT_ENDOFSCRIPT must be true when this function exit with 0. Turn _exit_code to 1."; _exit_code=1;
-    	else
-    	    echo "${_FUNC_MSG_PREFIX} _exit_code cannot be 0 for this func. Make sure you are calling this in a right context."; _exit_code=1;
-    	fi
+    local exit_code=${2:-$?} #
+    if [ -n $1 ]; then
+        echo "\e[31m$1\e0m" # print error in red
+    fi
+    if [ "$exit_code" == "0" ]; then # 0 is not error
```
Comment (130s) [inline industrial_ci/util.sh]: I assume this if block is added to handle mis-use? If so printing so would be friendly to the users?

File: industrial_ci/util.sh [hunk 5]
```diff
@@ -51,93 +51,76 @@ function ici_time_start {
...
+        if [ $exit_code -ne "0" ]; then color_wrap=31; fi  # Red color for errors
+        ici_time_end "$color_wrap" "$exit_code"
     fi
 
-    if [ $exit_code -eq "1" ]; then trap - ERR; fi  # Reset signal handler since the shell is about to exit.
-    if [ "$DEBUG_BASH" ] && [ "$DEBUG_BASH" == true ]; then set -x; fi
-    if [ $exit_code -ne "-1" ]; then exit $exit_code; fi
+    if [ "$exit_code" == "${EXPECT_EXIT_CODE:-0}" ]; then
+        exit 0
+    elif [ "$exit_code" == "0" ]; then # 0 was not expected
```
Comment (130s) [inline industrial_ci/util.sh]: Same as https://github.com/ros-industrial/industrial_ci/pull/103/files#r96508040

**Comment by 130s** [comment]
Left a minor comment.

>  Now every fold lists an exit code and error forwards the exit code if possible.

That looks convenient!

File: industrial_ci/util.sh (hunk 4 above)
Comment (ipa-mdl) [inline industrial_ci/util.sh]: exit_code is read from $?, which might be 0 in some cases, like `if ! false ; then echo "$?"; fi`.
So the following code works now as expected:
```bash
if ! [ -e "$my_path" ]; then
  error "path does not exist: '$my_path'"
fi
```
I think, the documentation needs to be updated..

File: industrial_ci/util.sh (hunk 5 above)
Comment (ipa-mdl) [inline industrial_ci/util.sh]: No, this is another use case.

If exit_code != EXPECT_EXIT_CODE  then the exit_code will be used.
However, If exit_code is 0, but EXPECT_EXIT_CODE is not 0, the exit_code can not be returned as 0 would mean success.

File: industrial_ci/util.sh (hunk 4 above)
Comment (ipa-mdl) [inline industrial_ci/util.sh]: Alternative implementation, with exit_code passing:
```
test -e "$my_path" || error "path does not exist: '$my_path'"
```

**Comment by ipa-mdl** [comment]
If you do not object, I will merge this PR tomorrow (= in 10 hours) :)
